---
title: "demo"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(mhcnuggetsr)
library(testthat)
```

For this vignette, we use the same example as the MHCnuggets
Python notebooks.

```{r}
if (is_mhcnuggets_installed()) {
  peptides_path <- get_example_filename("test_peptides.peps")
  expect_true(file.exists(peptides_path))
}
```

```{r}
if (is_mhcnuggets_installed()) {
  mhc_1_haplotype <- "HLA-A02:01"
  expect_true(mhc_1_haplotype %in% get_trained_mhc_1_haplotypes())
}
```

```
if (is_mhcnuggets_installed()) {
  epitope_predict(
    class_='I',
    peptides_path = peptides_path, 
    mhc = mhc_1_haplotype
  )
}
```



```
if (is_mhcnuggets_installed()) {
  epitope_predict(
    class_='I',
    peptides_path = peptides_path, 
    mhc = mhc_1_haplotype, 
    ba_models = TRUE
  )
}
```

```{r}
if (is_mhcnuggets_installed()) {
  mhc_2_haplotype <- "HLA-DRB101:01"
  expect_true(mhc_2_haplotype %in% get_trained_mhc_2_haplotypes())
}
```

```
if (is_mhcnuggets_installed()) {
  epitope_predict(
    class_='II',
    peptides_path = peptides_path, 
    mhc = mhc_2_haplotype
  )
}
```

```{r}
if (is_mhcnuggets_installed()) {
  mhc_1_haplotype <- "HLA-A02:60"
  # This is not true, no idea why
  # expect_true(mhc_1_haplotype %in% get_trained_mhc_1_haplotypes())
}
```

```
if (is_mhcnuggets_installed()) {
  epitope_predict(
    class_='I',
    peptides_path = peptides_path, 
    mhc = mhc_1_haplotype
  )
}
```

## Appendix

### All example files

```{r}
if (is_mhcnuggets_installed()) {
  get_example_filenames()
}
```

### All MHC-I haplotypes

These are the MHC-I haplotypes that have a trained model.

```{r}
if (is_mhcnuggets_installed()) {
  get_trained_mhc_1_haplotypes()
}
```

### All MHC-II haplotypes

These are the MHC-II haplotypes that have a trained model.

```{r}
if (is_mhcnuggets_installed()) {
  get_trained_mhc_2_haplotypes()
}
```

### Session info

```{r}
mhcnuggetsr_report()
```
