test_that("use", {
  if (!is_on_ci()) return()
  if (!is_mhcnuggets_installed()) return()

  expect_silent(set_is_mhcnuggets_installed(TRUE))
  expect_true(is_mhcnuggets_installed())
  expect_silent(set_is_mhcnuggets_installed(FALSE))
  expect_true(!is_mhcnuggets_installed())
  expect_silent(set_is_mhcnuggets_installed(FALSE))
  expect_true(!is_mhcnuggets_installed())
  expect_silent(set_is_mhcnuggets_installed(TRUE))
  expect_true(is_mhcnuggets_installed())
  expect_silent(set_is_mhcnuggets_installed(TRUE))
  expect_true(is_mhcnuggets_installed())
})
