test_that("use", {
  if (!is_mhcnuggets_installed()) return()
  expect_true(!is_mhcnuggets_name(mhc = "HLA-A*01:01"))
  expect_true(is_mhcnuggets_name(mhc = "HLA-A01:01"))
  expect_false(is_mhcnuggets_name(NA))
  expect_false(is_mhcnuggets_name(NULL))
  expect_false(is_mhcnuggets_name(Inf))
  expect_false(is_mhcnuggets_name(""))
  expect_false(is_mhcnuggets_name(c()))
  expect_false(is_mhcnuggets_name(character(0)))
  expect_false(is_mhcnuggets_name("nonsense"))
  expect_false(is_mhcnuggets_name(c("nonsense", "HLA-A01:01")))
  expect_false(is_mhcnuggets_name(c("HLA-A01:01", "HLA-A01:01")))
})
